//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	imagev1 "github.com/openshift/api/image/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1 "k8s.io/kubernetes/pkg/apis/core/v1"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&imagev1.ImageStream{}, func(obj interface{}) { SetObjectDefaults_ImageStream(obj.(*imagev1.ImageStream)) })
	scheme.AddTypeDefaultingFunc(&imagev1.ImageStreamImport{}, func(obj interface{}) { SetObjectDefaults_ImageStreamImport(obj.(*imagev1.ImageStreamImport)) })
	scheme.AddTypeDefaultingFunc(&imagev1.ImageStreamList{}, func(obj interface{}) { SetObjectDefaults_ImageStreamList(obj.(*imagev1.ImageStreamList)) })
	scheme.AddTypeDefaultingFunc(&imagev1.ImageStreamTag{}, func(obj interface{}) { SetObjectDefaults_ImageStreamTag(obj.(*imagev1.ImageStreamTag)) })
	scheme.AddTypeDefaultingFunc(&imagev1.ImageStreamTagList{}, func(obj interface{}) { SetObjectDefaults_ImageStreamTagList(obj.(*imagev1.ImageStreamTagList)) })
	scheme.AddTypeDefaultingFunc(&imagev1.ImageTag{}, func(obj interface{}) { SetObjectDefaults_ImageTag(obj.(*imagev1.ImageTag)) })
	scheme.AddTypeDefaultingFunc(&imagev1.ImageTagList{}, func(obj interface{}) { SetObjectDefaults_ImageTagList(obj.(*imagev1.ImageTagList)) })
	scheme.AddTypeDefaultingFunc(&imagev1.SecretList{}, func(obj interface{}) { SetObjectDefaults_SecretList(obj.(*imagev1.SecretList)) })
	return nil
}

func SetObjectDefaults_ImageStream(in *imagev1.ImageStream) {
	for i := range in.Spec.Tags {
		a := &in.Spec.Tags[i]
		SetDefaults_TagImportPolicy(&a.ImportPolicy)
		SetDefaults_TagReferencePolicy(&a.ReferencePolicy)
	}
}

func SetObjectDefaults_ImageStreamImport(in *imagev1.ImageStreamImport) {
	if in.Spec.Repository != nil {
		SetDefaults_TagImportPolicy(&in.Spec.Repository.ImportPolicy)
		SetDefaults_TagReferencePolicy(&in.Spec.Repository.ReferencePolicy)
	}
	for i := range in.Spec.Images {
		a := &in.Spec.Images[i]
		SetDefaults_ImageImportSpec(a)
		SetDefaults_TagImportPolicy(&a.ImportPolicy)
		SetDefaults_TagReferencePolicy(&a.ReferencePolicy)
	}
	if in.Status.Import != nil {
		SetObjectDefaults_ImageStream(in.Status.Import)
	}
}

func SetObjectDefaults_ImageStreamList(in *imagev1.ImageStreamList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ImageStream(a)
	}
}

func SetObjectDefaults_ImageStreamTag(in *imagev1.ImageStreamTag) {
	if in.Tag != nil {
		SetDefaults_TagImportPolicy(&in.Tag.ImportPolicy)
		SetDefaults_TagReferencePolicy(&in.Tag.ReferencePolicy)
	}
}

func SetObjectDefaults_ImageStreamTagList(in *imagev1.ImageStreamTagList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ImageStreamTag(a)
	}
}

func SetObjectDefaults_ImageTag(in *imagev1.ImageTag) {
	if in.Spec != nil {
		SetDefaults_TagImportPolicy(&in.Spec.ImportPolicy)
		SetDefaults_TagReferencePolicy(&in.Spec.ReferencePolicy)
	}
}

func SetObjectDefaults_ImageTagList(in *imagev1.ImageTagList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ImageTag(a)
	}
}

func SetObjectDefaults_SecretList(in *imagev1.SecretList) {
	for i := range in.Items {
		a := &in.Items[i]
		corev1.SetObjectDefaults_Secret(a)
	}
}
