//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	authorizationv1 "github.com/openshift/api/authorization/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&authorizationv1.ClusterRole{}, func(obj interface{}) { SetObjectDefaults_ClusterRole(obj.(*authorizationv1.ClusterRole)) })
	scheme.AddTypeDefaultingFunc(&authorizationv1.ClusterRoleList{}, func(obj interface{}) { SetObjectDefaults_ClusterRoleList(obj.(*authorizationv1.ClusterRoleList)) })
	scheme.AddTypeDefaultingFunc(&authorizationv1.Role{}, func(obj interface{}) { SetObjectDefaults_Role(obj.(*authorizationv1.Role)) })
	scheme.AddTypeDefaultingFunc(&authorizationv1.RoleList{}, func(obj interface{}) { SetObjectDefaults_RoleList(obj.(*authorizationv1.RoleList)) })
	scheme.AddTypeDefaultingFunc(&authorizationv1.SelfSubjectRulesReview{}, func(obj interface{}) {
		SetObjectDefaults_SelfSubjectRulesReview(obj.(*authorizationv1.SelfSubjectRulesReview))
	})
	scheme.AddTypeDefaultingFunc(&authorizationv1.SubjectRulesReview{}, func(obj interface{}) { SetObjectDefaults_SubjectRulesReview(obj.(*authorizationv1.SubjectRulesReview)) })
	return nil
}

func SetObjectDefaults_ClusterRole(in *authorizationv1.ClusterRole) {
	for i := range in.Rules {
		a := &in.Rules[i]
		SetDefaults_PolicyRule(a)
	}
}

func SetObjectDefaults_ClusterRoleList(in *authorizationv1.ClusterRoleList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ClusterRole(a)
	}
}

func SetObjectDefaults_Role(in *authorizationv1.Role) {
	for i := range in.Rules {
		a := &in.Rules[i]
		SetDefaults_PolicyRule(a)
	}
}

func SetObjectDefaults_RoleList(in *authorizationv1.RoleList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Role(a)
	}
}

func SetObjectDefaults_SelfSubjectRulesReview(in *authorizationv1.SelfSubjectRulesReview) {
	for i := range in.Status.Rules {
		a := &in.Status.Rules[i]
		SetDefaults_PolicyRule(a)
	}
}

func SetObjectDefaults_SubjectRulesReview(in *authorizationv1.SubjectRulesReview) {
	for i := range in.Status.Rules {
		a := &in.Status.Rules[i]
		SetDefaults_PolicyRule(a)
	}
}
