//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	quotav1 "github.com/openshift/api/quota/v1"
	quota "github.com/openshift/openshift-apiserver/pkg/quota/apis/quota"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1 "k8s.io/kubernetes/pkg/apis/core/v1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*quotav1.AppliedClusterResourceQuota)(nil), (*quota.AppliedClusterResourceQuota)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AppliedClusterResourceQuota_To_quota_AppliedClusterResourceQuota(a.(*quotav1.AppliedClusterResourceQuota), b.(*quota.AppliedClusterResourceQuota), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quota.AppliedClusterResourceQuota)(nil), (*quotav1.AppliedClusterResourceQuota)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_quota_AppliedClusterResourceQuota_To_v1_AppliedClusterResourceQuota(a.(*quota.AppliedClusterResourceQuota), b.(*quotav1.AppliedClusterResourceQuota), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quotav1.AppliedClusterResourceQuotaList)(nil), (*quota.AppliedClusterResourceQuotaList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AppliedClusterResourceQuotaList_To_quota_AppliedClusterResourceQuotaList(a.(*quotav1.AppliedClusterResourceQuotaList), b.(*quota.AppliedClusterResourceQuotaList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quota.AppliedClusterResourceQuotaList)(nil), (*quotav1.AppliedClusterResourceQuotaList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_quota_AppliedClusterResourceQuotaList_To_v1_AppliedClusterResourceQuotaList(a.(*quota.AppliedClusterResourceQuotaList), b.(*quotav1.AppliedClusterResourceQuotaList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quotav1.ClusterResourceQuota)(nil), (*quota.ClusterResourceQuota)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterResourceQuota_To_quota_ClusterResourceQuota(a.(*quotav1.ClusterResourceQuota), b.(*quota.ClusterResourceQuota), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quota.ClusterResourceQuota)(nil), (*quotav1.ClusterResourceQuota)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_quota_ClusterResourceQuota_To_v1_ClusterResourceQuota(a.(*quota.ClusterResourceQuota), b.(*quotav1.ClusterResourceQuota), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quotav1.ClusterResourceQuotaList)(nil), (*quota.ClusterResourceQuotaList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterResourceQuotaList_To_quota_ClusterResourceQuotaList(a.(*quotav1.ClusterResourceQuotaList), b.(*quota.ClusterResourceQuotaList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quota.ClusterResourceQuotaList)(nil), (*quotav1.ClusterResourceQuotaList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_quota_ClusterResourceQuotaList_To_v1_ClusterResourceQuotaList(a.(*quota.ClusterResourceQuotaList), b.(*quotav1.ClusterResourceQuotaList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quotav1.ClusterResourceQuotaSelector)(nil), (*quota.ClusterResourceQuotaSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterResourceQuotaSelector_To_quota_ClusterResourceQuotaSelector(a.(*quotav1.ClusterResourceQuotaSelector), b.(*quota.ClusterResourceQuotaSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quota.ClusterResourceQuotaSelector)(nil), (*quotav1.ClusterResourceQuotaSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_quota_ClusterResourceQuotaSelector_To_v1_ClusterResourceQuotaSelector(a.(*quota.ClusterResourceQuotaSelector), b.(*quotav1.ClusterResourceQuotaSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quotav1.ClusterResourceQuotaSpec)(nil), (*quota.ClusterResourceQuotaSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterResourceQuotaSpec_To_quota_ClusterResourceQuotaSpec(a.(*quotav1.ClusterResourceQuotaSpec), b.(*quota.ClusterResourceQuotaSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quota.ClusterResourceQuotaSpec)(nil), (*quotav1.ClusterResourceQuotaSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_quota_ClusterResourceQuotaSpec_To_v1_ClusterResourceQuotaSpec(a.(*quota.ClusterResourceQuotaSpec), b.(*quotav1.ClusterResourceQuotaSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quotav1.ClusterResourceQuotaStatus)(nil), (*quota.ClusterResourceQuotaStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterResourceQuotaStatus_To_quota_ClusterResourceQuotaStatus(a.(*quotav1.ClusterResourceQuotaStatus), b.(*quota.ClusterResourceQuotaStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*quota.ClusterResourceQuotaStatus)(nil), (*quotav1.ClusterResourceQuotaStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_quota_ClusterResourceQuotaStatus_To_v1_ClusterResourceQuotaStatus(a.(*quota.ClusterResourceQuotaStatus), b.(*quotav1.ClusterResourceQuotaStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*quota.ResourceQuotasStatusByNamespace)(nil), (*quotav1.ResourceQuotasStatusByNamespace)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_quota_ResourceQuotasStatusByNamespace_To_v1_ResourceQuotasStatusByNamespace(a.(*quota.ResourceQuotasStatusByNamespace), b.(*quotav1.ResourceQuotasStatusByNamespace), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*quotav1.ResourceQuotasStatusByNamespace)(nil), (*quota.ResourceQuotasStatusByNamespace)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ResourceQuotasStatusByNamespace_To_quota_ResourceQuotasStatusByNamespace(a.(*quotav1.ResourceQuotasStatusByNamespace), b.(*quota.ResourceQuotasStatusByNamespace), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_AppliedClusterResourceQuota_To_quota_AppliedClusterResourceQuota(in *quotav1.AppliedClusterResourceQuota, out *quota.AppliedClusterResourceQuota, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ClusterResourceQuotaSpec_To_quota_ClusterResourceQuotaSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ClusterResourceQuotaStatus_To_quota_ClusterResourceQuotaStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_AppliedClusterResourceQuota_To_quota_AppliedClusterResourceQuota is an autogenerated conversion function.
func Convert_v1_AppliedClusterResourceQuota_To_quota_AppliedClusterResourceQuota(in *quotav1.AppliedClusterResourceQuota, out *quota.AppliedClusterResourceQuota, s conversion.Scope) error {
	return autoConvert_v1_AppliedClusterResourceQuota_To_quota_AppliedClusterResourceQuota(in, out, s)
}

func autoConvert_quota_AppliedClusterResourceQuota_To_v1_AppliedClusterResourceQuota(in *quota.AppliedClusterResourceQuota, out *quotav1.AppliedClusterResourceQuota, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_quota_ClusterResourceQuotaSpec_To_v1_ClusterResourceQuotaSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_quota_ClusterResourceQuotaStatus_To_v1_ClusterResourceQuotaStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_quota_AppliedClusterResourceQuota_To_v1_AppliedClusterResourceQuota is an autogenerated conversion function.
func Convert_quota_AppliedClusterResourceQuota_To_v1_AppliedClusterResourceQuota(in *quota.AppliedClusterResourceQuota, out *quotav1.AppliedClusterResourceQuota, s conversion.Scope) error {
	return autoConvert_quota_AppliedClusterResourceQuota_To_v1_AppliedClusterResourceQuota(in, out, s)
}

func autoConvert_v1_AppliedClusterResourceQuotaList_To_quota_AppliedClusterResourceQuotaList(in *quotav1.AppliedClusterResourceQuotaList, out *quota.AppliedClusterResourceQuotaList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]quota.AppliedClusterResourceQuota, len(*in))
		for i := range *in {
			if err := Convert_v1_AppliedClusterResourceQuota_To_quota_AppliedClusterResourceQuota(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1_AppliedClusterResourceQuotaList_To_quota_AppliedClusterResourceQuotaList is an autogenerated conversion function.
func Convert_v1_AppliedClusterResourceQuotaList_To_quota_AppliedClusterResourceQuotaList(in *quotav1.AppliedClusterResourceQuotaList, out *quota.AppliedClusterResourceQuotaList, s conversion.Scope) error {
	return autoConvert_v1_AppliedClusterResourceQuotaList_To_quota_AppliedClusterResourceQuotaList(in, out, s)
}

func autoConvert_quota_AppliedClusterResourceQuotaList_To_v1_AppliedClusterResourceQuotaList(in *quota.AppliedClusterResourceQuotaList, out *quotav1.AppliedClusterResourceQuotaList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]quotav1.AppliedClusterResourceQuota, len(*in))
		for i := range *in {
			if err := Convert_quota_AppliedClusterResourceQuota_To_v1_AppliedClusterResourceQuota(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_quota_AppliedClusterResourceQuotaList_To_v1_AppliedClusterResourceQuotaList is an autogenerated conversion function.
func Convert_quota_AppliedClusterResourceQuotaList_To_v1_AppliedClusterResourceQuotaList(in *quota.AppliedClusterResourceQuotaList, out *quotav1.AppliedClusterResourceQuotaList, s conversion.Scope) error {
	return autoConvert_quota_AppliedClusterResourceQuotaList_To_v1_AppliedClusterResourceQuotaList(in, out, s)
}

func autoConvert_v1_ClusterResourceQuota_To_quota_ClusterResourceQuota(in *quotav1.ClusterResourceQuota, out *quota.ClusterResourceQuota, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ClusterResourceQuotaSpec_To_quota_ClusterResourceQuotaSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ClusterResourceQuotaStatus_To_quota_ClusterResourceQuotaStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ClusterResourceQuota_To_quota_ClusterResourceQuota is an autogenerated conversion function.
func Convert_v1_ClusterResourceQuota_To_quota_ClusterResourceQuota(in *quotav1.ClusterResourceQuota, out *quota.ClusterResourceQuota, s conversion.Scope) error {
	return autoConvert_v1_ClusterResourceQuota_To_quota_ClusterResourceQuota(in, out, s)
}

func autoConvert_quota_ClusterResourceQuota_To_v1_ClusterResourceQuota(in *quota.ClusterResourceQuota, out *quotav1.ClusterResourceQuota, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_quota_ClusterResourceQuotaSpec_To_v1_ClusterResourceQuotaSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_quota_ClusterResourceQuotaStatus_To_v1_ClusterResourceQuotaStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_quota_ClusterResourceQuota_To_v1_ClusterResourceQuota is an autogenerated conversion function.
func Convert_quota_ClusterResourceQuota_To_v1_ClusterResourceQuota(in *quota.ClusterResourceQuota, out *quotav1.ClusterResourceQuota, s conversion.Scope) error {
	return autoConvert_quota_ClusterResourceQuota_To_v1_ClusterResourceQuota(in, out, s)
}

func autoConvert_v1_ClusterResourceQuotaList_To_quota_ClusterResourceQuotaList(in *quotav1.ClusterResourceQuotaList, out *quota.ClusterResourceQuotaList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]quota.ClusterResourceQuota, len(*in))
		for i := range *in {
			if err := Convert_v1_ClusterResourceQuota_To_quota_ClusterResourceQuota(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1_ClusterResourceQuotaList_To_quota_ClusterResourceQuotaList is an autogenerated conversion function.
func Convert_v1_ClusterResourceQuotaList_To_quota_ClusterResourceQuotaList(in *quotav1.ClusterResourceQuotaList, out *quota.ClusterResourceQuotaList, s conversion.Scope) error {
	return autoConvert_v1_ClusterResourceQuotaList_To_quota_ClusterResourceQuotaList(in, out, s)
}

func autoConvert_quota_ClusterResourceQuotaList_To_v1_ClusterResourceQuotaList(in *quota.ClusterResourceQuotaList, out *quotav1.ClusterResourceQuotaList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]quotav1.ClusterResourceQuota, len(*in))
		for i := range *in {
			if err := Convert_quota_ClusterResourceQuota_To_v1_ClusterResourceQuota(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_quota_ClusterResourceQuotaList_To_v1_ClusterResourceQuotaList is an autogenerated conversion function.
func Convert_quota_ClusterResourceQuotaList_To_v1_ClusterResourceQuotaList(in *quota.ClusterResourceQuotaList, out *quotav1.ClusterResourceQuotaList, s conversion.Scope) error {
	return autoConvert_quota_ClusterResourceQuotaList_To_v1_ClusterResourceQuotaList(in, out, s)
}

func autoConvert_v1_ClusterResourceQuotaSelector_To_quota_ClusterResourceQuotaSelector(in *quotav1.ClusterResourceQuotaSelector, out *quota.ClusterResourceQuotaSelector, s conversion.Scope) error {
	out.LabelSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.LabelSelector))
	out.AnnotationSelector = *(*map[string]string)(unsafe.Pointer(&in.AnnotationSelector))
	return nil
}

// Convert_v1_ClusterResourceQuotaSelector_To_quota_ClusterResourceQuotaSelector is an autogenerated conversion function.
func Convert_v1_ClusterResourceQuotaSelector_To_quota_ClusterResourceQuotaSelector(in *quotav1.ClusterResourceQuotaSelector, out *quota.ClusterResourceQuotaSelector, s conversion.Scope) error {
	return autoConvert_v1_ClusterResourceQuotaSelector_To_quota_ClusterResourceQuotaSelector(in, out, s)
}

func autoConvert_quota_ClusterResourceQuotaSelector_To_v1_ClusterResourceQuotaSelector(in *quota.ClusterResourceQuotaSelector, out *quotav1.ClusterResourceQuotaSelector, s conversion.Scope) error {
	out.LabelSelector = (*metav1.LabelSelector)(unsafe.Pointer(in.LabelSelector))
	out.AnnotationSelector = *(*map[string]string)(unsafe.Pointer(&in.AnnotationSelector))
	return nil
}

// Convert_quota_ClusterResourceQuotaSelector_To_v1_ClusterResourceQuotaSelector is an autogenerated conversion function.
func Convert_quota_ClusterResourceQuotaSelector_To_v1_ClusterResourceQuotaSelector(in *quota.ClusterResourceQuotaSelector, out *quotav1.ClusterResourceQuotaSelector, s conversion.Scope) error {
	return autoConvert_quota_ClusterResourceQuotaSelector_To_v1_ClusterResourceQuotaSelector(in, out, s)
}

func autoConvert_v1_ClusterResourceQuotaSpec_To_quota_ClusterResourceQuotaSpec(in *quotav1.ClusterResourceQuotaSpec, out *quota.ClusterResourceQuotaSpec, s conversion.Scope) error {
	if err := Convert_v1_ClusterResourceQuotaSelector_To_quota_ClusterResourceQuotaSelector(&in.Selector, &out.Selector, s); err != nil {
		return err
	}
	if err := corev1.Convert_v1_ResourceQuotaSpec_To_core_ResourceQuotaSpec(&in.Quota, &out.Quota, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ClusterResourceQuotaSpec_To_quota_ClusterResourceQuotaSpec is an autogenerated conversion function.
func Convert_v1_ClusterResourceQuotaSpec_To_quota_ClusterResourceQuotaSpec(in *quotav1.ClusterResourceQuotaSpec, out *quota.ClusterResourceQuotaSpec, s conversion.Scope) error {
	return autoConvert_v1_ClusterResourceQuotaSpec_To_quota_ClusterResourceQuotaSpec(in, out, s)
}

func autoConvert_quota_ClusterResourceQuotaSpec_To_v1_ClusterResourceQuotaSpec(in *quota.ClusterResourceQuotaSpec, out *quotav1.ClusterResourceQuotaSpec, s conversion.Scope) error {
	if err := Convert_quota_ClusterResourceQuotaSelector_To_v1_ClusterResourceQuotaSelector(&in.Selector, &out.Selector, s); err != nil {
		return err
	}
	if err := corev1.Convert_core_ResourceQuotaSpec_To_v1_ResourceQuotaSpec(&in.Quota, &out.Quota, s); err != nil {
		return err
	}
	return nil
}

// Convert_quota_ClusterResourceQuotaSpec_To_v1_ClusterResourceQuotaSpec is an autogenerated conversion function.
func Convert_quota_ClusterResourceQuotaSpec_To_v1_ClusterResourceQuotaSpec(in *quota.ClusterResourceQuotaSpec, out *quotav1.ClusterResourceQuotaSpec, s conversion.Scope) error {
	return autoConvert_quota_ClusterResourceQuotaSpec_To_v1_ClusterResourceQuotaSpec(in, out, s)
}

func autoConvert_v1_ClusterResourceQuotaStatus_To_quota_ClusterResourceQuotaStatus(in *quotav1.ClusterResourceQuotaStatus, out *quota.ClusterResourceQuotaStatus, s conversion.Scope) error {
	if err := corev1.Convert_v1_ResourceQuotaStatus_To_core_ResourceQuotaStatus(&in.Total, &out.Total, s); err != nil {
		return err
	}
	if err := Convert_v1_ResourceQuotasStatusByNamespace_To_quota_ResourceQuotasStatusByNamespace(&in.Namespaces, &out.Namespaces, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ClusterResourceQuotaStatus_To_quota_ClusterResourceQuotaStatus is an autogenerated conversion function.
func Convert_v1_ClusterResourceQuotaStatus_To_quota_ClusterResourceQuotaStatus(in *quotav1.ClusterResourceQuotaStatus, out *quota.ClusterResourceQuotaStatus, s conversion.Scope) error {
	return autoConvert_v1_ClusterResourceQuotaStatus_To_quota_ClusterResourceQuotaStatus(in, out, s)
}

func autoConvert_quota_ClusterResourceQuotaStatus_To_v1_ClusterResourceQuotaStatus(in *quota.ClusterResourceQuotaStatus, out *quotav1.ClusterResourceQuotaStatus, s conversion.Scope) error {
	if err := corev1.Convert_core_ResourceQuotaStatus_To_v1_ResourceQuotaStatus(&in.Total, &out.Total, s); err != nil {
		return err
	}
	if err := Convert_quota_ResourceQuotasStatusByNamespace_To_v1_ResourceQuotasStatusByNamespace(&in.Namespaces, &out.Namespaces, s); err != nil {
		return err
	}
	return nil
}

// Convert_quota_ClusterResourceQuotaStatus_To_v1_ClusterResourceQuotaStatus is an autogenerated conversion function.
func Convert_quota_ClusterResourceQuotaStatus_To_v1_ClusterResourceQuotaStatus(in *quota.ClusterResourceQuotaStatus, out *quotav1.ClusterResourceQuotaStatus, s conversion.Scope) error {
	return autoConvert_quota_ClusterResourceQuotaStatus_To_v1_ClusterResourceQuotaStatus(in, out, s)
}
