//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	routev1 "github.com/openshift/api/route/v1"
	route "github.com/openshift/openshift-apiserver/pkg/route/apis/route"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	core "k8s.io/kubernetes/pkg/apis/core"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*routev1.LocalObjectReference)(nil), (*route.LocalObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LocalObjectReference_To_route_LocalObjectReference(a.(*routev1.LocalObjectReference), b.(*route.LocalObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.LocalObjectReference)(nil), (*routev1.LocalObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_LocalObjectReference_To_v1_LocalObjectReference(a.(*route.LocalObjectReference), b.(*routev1.LocalObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.Route)(nil), (*route.Route)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Route_To_route_Route(a.(*routev1.Route), b.(*route.Route), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.Route)(nil), (*routev1.Route)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_Route_To_v1_Route(a.(*route.Route), b.(*routev1.Route), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteHTTPHeader)(nil), (*route.RouteHTTPHeader)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteHTTPHeader_To_route_RouteHTTPHeader(a.(*routev1.RouteHTTPHeader), b.(*route.RouteHTTPHeader), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteHTTPHeader)(nil), (*routev1.RouteHTTPHeader)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteHTTPHeader_To_v1_RouteHTTPHeader(a.(*route.RouteHTTPHeader), b.(*routev1.RouteHTTPHeader), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteHTTPHeaderActionUnion)(nil), (*route.RouteHTTPHeaderActionUnion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteHTTPHeaderActionUnion_To_route_RouteHTTPHeaderActionUnion(a.(*routev1.RouteHTTPHeaderActionUnion), b.(*route.RouteHTTPHeaderActionUnion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteHTTPHeaderActionUnion)(nil), (*routev1.RouteHTTPHeaderActionUnion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteHTTPHeaderActionUnion_To_v1_RouteHTTPHeaderActionUnion(a.(*route.RouteHTTPHeaderActionUnion), b.(*routev1.RouteHTTPHeaderActionUnion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteHTTPHeaderActions)(nil), (*route.RouteHTTPHeaderActions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteHTTPHeaderActions_To_route_RouteHTTPHeaderActions(a.(*routev1.RouteHTTPHeaderActions), b.(*route.RouteHTTPHeaderActions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteHTTPHeaderActions)(nil), (*routev1.RouteHTTPHeaderActions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteHTTPHeaderActions_To_v1_RouteHTTPHeaderActions(a.(*route.RouteHTTPHeaderActions), b.(*routev1.RouteHTTPHeaderActions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteHTTPHeaders)(nil), (*route.RouteHTTPHeaders)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteHTTPHeaders_To_route_RouteHTTPHeaders(a.(*routev1.RouteHTTPHeaders), b.(*route.RouteHTTPHeaders), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteHTTPHeaders)(nil), (*routev1.RouteHTTPHeaders)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteHTTPHeaders_To_v1_RouteHTTPHeaders(a.(*route.RouteHTTPHeaders), b.(*routev1.RouteHTTPHeaders), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteIngress)(nil), (*route.RouteIngress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteIngress_To_route_RouteIngress(a.(*routev1.RouteIngress), b.(*route.RouteIngress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteIngress)(nil), (*routev1.RouteIngress)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteIngress_To_v1_RouteIngress(a.(*route.RouteIngress), b.(*routev1.RouteIngress), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteIngressCondition)(nil), (*route.RouteIngressCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteIngressCondition_To_route_RouteIngressCondition(a.(*routev1.RouteIngressCondition), b.(*route.RouteIngressCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteIngressCondition)(nil), (*routev1.RouteIngressCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteIngressCondition_To_v1_RouteIngressCondition(a.(*route.RouteIngressCondition), b.(*routev1.RouteIngressCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteList)(nil), (*route.RouteList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteList_To_route_RouteList(a.(*routev1.RouteList), b.(*route.RouteList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteList)(nil), (*routev1.RouteList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteList_To_v1_RouteList(a.(*route.RouteList), b.(*routev1.RouteList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RoutePort)(nil), (*route.RoutePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RoutePort_To_route_RoutePort(a.(*routev1.RoutePort), b.(*route.RoutePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RoutePort)(nil), (*routev1.RoutePort)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RoutePort_To_v1_RoutePort(a.(*route.RoutePort), b.(*routev1.RoutePort), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteSetHTTPHeader)(nil), (*route.RouteSetHTTPHeader)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteSetHTTPHeader_To_route_RouteSetHTTPHeader(a.(*routev1.RouteSetHTTPHeader), b.(*route.RouteSetHTTPHeader), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteSetHTTPHeader)(nil), (*routev1.RouteSetHTTPHeader)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteSetHTTPHeader_To_v1_RouteSetHTTPHeader(a.(*route.RouteSetHTTPHeader), b.(*routev1.RouteSetHTTPHeader), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteSpec)(nil), (*route.RouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteSpec_To_route_RouteSpec(a.(*routev1.RouteSpec), b.(*route.RouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteSpec)(nil), (*routev1.RouteSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteSpec_To_v1_RouteSpec(a.(*route.RouteSpec), b.(*routev1.RouteSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteStatus)(nil), (*route.RouteStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteStatus_To_route_RouteStatus(a.(*routev1.RouteStatus), b.(*route.RouteStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteStatus)(nil), (*routev1.RouteStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteStatus_To_v1_RouteStatus(a.(*route.RouteStatus), b.(*routev1.RouteStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouteTargetReference)(nil), (*route.RouteTargetReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouteTargetReference_To_route_RouteTargetReference(a.(*routev1.RouteTargetReference), b.(*route.RouteTargetReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouteTargetReference)(nil), (*routev1.RouteTargetReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouteTargetReference_To_v1_RouteTargetReference(a.(*route.RouteTargetReference), b.(*routev1.RouteTargetReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.RouterShard)(nil), (*route.RouterShard)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RouterShard_To_route_RouterShard(a.(*routev1.RouterShard), b.(*route.RouterShard), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.RouterShard)(nil), (*routev1.RouterShard)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_RouterShard_To_v1_RouterShard(a.(*route.RouterShard), b.(*routev1.RouterShard), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*routev1.TLSConfig)(nil), (*route.TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TLSConfig_To_route_TLSConfig(a.(*routev1.TLSConfig), b.(*route.TLSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*route.TLSConfig)(nil), (*routev1.TLSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_route_TLSConfig_To_v1_TLSConfig(a.(*route.TLSConfig), b.(*routev1.TLSConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_LocalObjectReference_To_route_LocalObjectReference(in *routev1.LocalObjectReference, out *route.LocalObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1_LocalObjectReference_To_route_LocalObjectReference is an autogenerated conversion function.
func Convert_v1_LocalObjectReference_To_route_LocalObjectReference(in *routev1.LocalObjectReference, out *route.LocalObjectReference, s conversion.Scope) error {
	return autoConvert_v1_LocalObjectReference_To_route_LocalObjectReference(in, out, s)
}

func autoConvert_route_LocalObjectReference_To_v1_LocalObjectReference(in *route.LocalObjectReference, out *routev1.LocalObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_route_LocalObjectReference_To_v1_LocalObjectReference is an autogenerated conversion function.
func Convert_route_LocalObjectReference_To_v1_LocalObjectReference(in *route.LocalObjectReference, out *routev1.LocalObjectReference, s conversion.Scope) error {
	return autoConvert_route_LocalObjectReference_To_v1_LocalObjectReference(in, out, s)
}

func autoConvert_v1_Route_To_route_Route(in *routev1.Route, out *route.Route, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_RouteSpec_To_route_RouteSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_RouteStatus_To_route_RouteStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Route_To_route_Route is an autogenerated conversion function.
func Convert_v1_Route_To_route_Route(in *routev1.Route, out *route.Route, s conversion.Scope) error {
	return autoConvert_v1_Route_To_route_Route(in, out, s)
}

func autoConvert_route_Route_To_v1_Route(in *route.Route, out *routev1.Route, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_route_RouteSpec_To_v1_RouteSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_route_RouteStatus_To_v1_RouteStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_route_Route_To_v1_Route is an autogenerated conversion function.
func Convert_route_Route_To_v1_Route(in *route.Route, out *routev1.Route, s conversion.Scope) error {
	return autoConvert_route_Route_To_v1_Route(in, out, s)
}

func autoConvert_v1_RouteHTTPHeader_To_route_RouteHTTPHeader(in *routev1.RouteHTTPHeader, out *route.RouteHTTPHeader, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1_RouteHTTPHeaderActionUnion_To_route_RouteHTTPHeaderActionUnion(&in.Action, &out.Action, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_RouteHTTPHeader_To_route_RouteHTTPHeader is an autogenerated conversion function.
func Convert_v1_RouteHTTPHeader_To_route_RouteHTTPHeader(in *routev1.RouteHTTPHeader, out *route.RouteHTTPHeader, s conversion.Scope) error {
	return autoConvert_v1_RouteHTTPHeader_To_route_RouteHTTPHeader(in, out, s)
}

func autoConvert_route_RouteHTTPHeader_To_v1_RouteHTTPHeader(in *route.RouteHTTPHeader, out *routev1.RouteHTTPHeader, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_route_RouteHTTPHeaderActionUnion_To_v1_RouteHTTPHeaderActionUnion(&in.Action, &out.Action, s); err != nil {
		return err
	}
	return nil
}

// Convert_route_RouteHTTPHeader_To_v1_RouteHTTPHeader is an autogenerated conversion function.
func Convert_route_RouteHTTPHeader_To_v1_RouteHTTPHeader(in *route.RouteHTTPHeader, out *routev1.RouteHTTPHeader, s conversion.Scope) error {
	return autoConvert_route_RouteHTTPHeader_To_v1_RouteHTTPHeader(in, out, s)
}

func autoConvert_v1_RouteHTTPHeaderActionUnion_To_route_RouteHTTPHeaderActionUnion(in *routev1.RouteHTTPHeaderActionUnion, out *route.RouteHTTPHeaderActionUnion, s conversion.Scope) error {
	out.Type = route.RouteHTTPHeaderActionType(in.Type)
	out.Set = (*route.RouteSetHTTPHeader)(unsafe.Pointer(in.Set))
	return nil
}

// Convert_v1_RouteHTTPHeaderActionUnion_To_route_RouteHTTPHeaderActionUnion is an autogenerated conversion function.
func Convert_v1_RouteHTTPHeaderActionUnion_To_route_RouteHTTPHeaderActionUnion(in *routev1.RouteHTTPHeaderActionUnion, out *route.RouteHTTPHeaderActionUnion, s conversion.Scope) error {
	return autoConvert_v1_RouteHTTPHeaderActionUnion_To_route_RouteHTTPHeaderActionUnion(in, out, s)
}

func autoConvert_route_RouteHTTPHeaderActionUnion_To_v1_RouteHTTPHeaderActionUnion(in *route.RouteHTTPHeaderActionUnion, out *routev1.RouteHTTPHeaderActionUnion, s conversion.Scope) error {
	out.Type = routev1.RouteHTTPHeaderActionType(in.Type)
	out.Set = (*routev1.RouteSetHTTPHeader)(unsafe.Pointer(in.Set))
	return nil
}

// Convert_route_RouteHTTPHeaderActionUnion_To_v1_RouteHTTPHeaderActionUnion is an autogenerated conversion function.
func Convert_route_RouteHTTPHeaderActionUnion_To_v1_RouteHTTPHeaderActionUnion(in *route.RouteHTTPHeaderActionUnion, out *routev1.RouteHTTPHeaderActionUnion, s conversion.Scope) error {
	return autoConvert_route_RouteHTTPHeaderActionUnion_To_v1_RouteHTTPHeaderActionUnion(in, out, s)
}

func autoConvert_v1_RouteHTTPHeaderActions_To_route_RouteHTTPHeaderActions(in *routev1.RouteHTTPHeaderActions, out *route.RouteHTTPHeaderActions, s conversion.Scope) error {
	out.Response = *(*[]route.RouteHTTPHeader)(unsafe.Pointer(&in.Response))
	out.Request = *(*[]route.RouteHTTPHeader)(unsafe.Pointer(&in.Request))
	return nil
}

// Convert_v1_RouteHTTPHeaderActions_To_route_RouteHTTPHeaderActions is an autogenerated conversion function.
func Convert_v1_RouteHTTPHeaderActions_To_route_RouteHTTPHeaderActions(in *routev1.RouteHTTPHeaderActions, out *route.RouteHTTPHeaderActions, s conversion.Scope) error {
	return autoConvert_v1_RouteHTTPHeaderActions_To_route_RouteHTTPHeaderActions(in, out, s)
}

func autoConvert_route_RouteHTTPHeaderActions_To_v1_RouteHTTPHeaderActions(in *route.RouteHTTPHeaderActions, out *routev1.RouteHTTPHeaderActions, s conversion.Scope) error {
	out.Response = *(*[]routev1.RouteHTTPHeader)(unsafe.Pointer(&in.Response))
	out.Request = *(*[]routev1.RouteHTTPHeader)(unsafe.Pointer(&in.Request))
	return nil
}

// Convert_route_RouteHTTPHeaderActions_To_v1_RouteHTTPHeaderActions is an autogenerated conversion function.
func Convert_route_RouteHTTPHeaderActions_To_v1_RouteHTTPHeaderActions(in *route.RouteHTTPHeaderActions, out *routev1.RouteHTTPHeaderActions, s conversion.Scope) error {
	return autoConvert_route_RouteHTTPHeaderActions_To_v1_RouteHTTPHeaderActions(in, out, s)
}

func autoConvert_v1_RouteHTTPHeaders_To_route_RouteHTTPHeaders(in *routev1.RouteHTTPHeaders, out *route.RouteHTTPHeaders, s conversion.Scope) error {
	if err := Convert_v1_RouteHTTPHeaderActions_To_route_RouteHTTPHeaderActions(&in.Actions, &out.Actions, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_RouteHTTPHeaders_To_route_RouteHTTPHeaders is an autogenerated conversion function.
func Convert_v1_RouteHTTPHeaders_To_route_RouteHTTPHeaders(in *routev1.RouteHTTPHeaders, out *route.RouteHTTPHeaders, s conversion.Scope) error {
	return autoConvert_v1_RouteHTTPHeaders_To_route_RouteHTTPHeaders(in, out, s)
}

func autoConvert_route_RouteHTTPHeaders_To_v1_RouteHTTPHeaders(in *route.RouteHTTPHeaders, out *routev1.RouteHTTPHeaders, s conversion.Scope) error {
	if err := Convert_route_RouteHTTPHeaderActions_To_v1_RouteHTTPHeaderActions(&in.Actions, &out.Actions, s); err != nil {
		return err
	}
	return nil
}

// Convert_route_RouteHTTPHeaders_To_v1_RouteHTTPHeaders is an autogenerated conversion function.
func Convert_route_RouteHTTPHeaders_To_v1_RouteHTTPHeaders(in *route.RouteHTTPHeaders, out *routev1.RouteHTTPHeaders, s conversion.Scope) error {
	return autoConvert_route_RouteHTTPHeaders_To_v1_RouteHTTPHeaders(in, out, s)
}

func autoConvert_v1_RouteIngress_To_route_RouteIngress(in *routev1.RouteIngress, out *route.RouteIngress, s conversion.Scope) error {
	out.Host = in.Host
	out.RouterName = in.RouterName
	out.Conditions = *(*[]route.RouteIngressCondition)(unsafe.Pointer(&in.Conditions))
	out.WildcardPolicy = route.WildcardPolicyType(in.WildcardPolicy)
	out.RouterCanonicalHostname = in.RouterCanonicalHostname
	return nil
}

// Convert_v1_RouteIngress_To_route_RouteIngress is an autogenerated conversion function.
func Convert_v1_RouteIngress_To_route_RouteIngress(in *routev1.RouteIngress, out *route.RouteIngress, s conversion.Scope) error {
	return autoConvert_v1_RouteIngress_To_route_RouteIngress(in, out, s)
}

func autoConvert_route_RouteIngress_To_v1_RouteIngress(in *route.RouteIngress, out *routev1.RouteIngress, s conversion.Scope) error {
	out.Host = in.Host
	out.RouterName = in.RouterName
	out.Conditions = *(*[]routev1.RouteIngressCondition)(unsafe.Pointer(&in.Conditions))
	out.WildcardPolicy = routev1.WildcardPolicyType(in.WildcardPolicy)
	out.RouterCanonicalHostname = in.RouterCanonicalHostname
	return nil
}

// Convert_route_RouteIngress_To_v1_RouteIngress is an autogenerated conversion function.
func Convert_route_RouteIngress_To_v1_RouteIngress(in *route.RouteIngress, out *routev1.RouteIngress, s conversion.Scope) error {
	return autoConvert_route_RouteIngress_To_v1_RouteIngress(in, out, s)
}

func autoConvert_v1_RouteIngressCondition_To_route_RouteIngressCondition(in *routev1.RouteIngressCondition, out *route.RouteIngressCondition, s conversion.Scope) error {
	out.Type = route.RouteIngressConditionType(in.Type)
	out.Status = core.ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = (*metav1.Time)(unsafe.Pointer(in.LastTransitionTime))
	return nil
}

// Convert_v1_RouteIngressCondition_To_route_RouteIngressCondition is an autogenerated conversion function.
func Convert_v1_RouteIngressCondition_To_route_RouteIngressCondition(in *routev1.RouteIngressCondition, out *route.RouteIngressCondition, s conversion.Scope) error {
	return autoConvert_v1_RouteIngressCondition_To_route_RouteIngressCondition(in, out, s)
}

func autoConvert_route_RouteIngressCondition_To_v1_RouteIngressCondition(in *route.RouteIngressCondition, out *routev1.RouteIngressCondition, s conversion.Scope) error {
	out.Type = routev1.RouteIngressConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = (*metav1.Time)(unsafe.Pointer(in.LastTransitionTime))
	return nil
}

// Convert_route_RouteIngressCondition_To_v1_RouteIngressCondition is an autogenerated conversion function.
func Convert_route_RouteIngressCondition_To_v1_RouteIngressCondition(in *route.RouteIngressCondition, out *routev1.RouteIngressCondition, s conversion.Scope) error {
	return autoConvert_route_RouteIngressCondition_To_v1_RouteIngressCondition(in, out, s)
}

func autoConvert_v1_RouteList_To_route_RouteList(in *routev1.RouteList, out *route.RouteList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]route.Route)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_RouteList_To_route_RouteList is an autogenerated conversion function.
func Convert_v1_RouteList_To_route_RouteList(in *routev1.RouteList, out *route.RouteList, s conversion.Scope) error {
	return autoConvert_v1_RouteList_To_route_RouteList(in, out, s)
}

func autoConvert_route_RouteList_To_v1_RouteList(in *route.RouteList, out *routev1.RouteList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]routev1.Route)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_route_RouteList_To_v1_RouteList is an autogenerated conversion function.
func Convert_route_RouteList_To_v1_RouteList(in *route.RouteList, out *routev1.RouteList, s conversion.Scope) error {
	return autoConvert_route_RouteList_To_v1_RouteList(in, out, s)
}

func autoConvert_v1_RoutePort_To_route_RoutePort(in *routev1.RoutePort, out *route.RoutePort, s conversion.Scope) error {
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_v1_RoutePort_To_route_RoutePort is an autogenerated conversion function.
func Convert_v1_RoutePort_To_route_RoutePort(in *routev1.RoutePort, out *route.RoutePort, s conversion.Scope) error {
	return autoConvert_v1_RoutePort_To_route_RoutePort(in, out, s)
}

func autoConvert_route_RoutePort_To_v1_RoutePort(in *route.RoutePort, out *routev1.RoutePort, s conversion.Scope) error {
	out.TargetPort = in.TargetPort
	return nil
}

// Convert_route_RoutePort_To_v1_RoutePort is an autogenerated conversion function.
func Convert_route_RoutePort_To_v1_RoutePort(in *route.RoutePort, out *routev1.RoutePort, s conversion.Scope) error {
	return autoConvert_route_RoutePort_To_v1_RoutePort(in, out, s)
}

func autoConvert_v1_RouteSetHTTPHeader_To_route_RouteSetHTTPHeader(in *routev1.RouteSetHTTPHeader, out *route.RouteSetHTTPHeader, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_v1_RouteSetHTTPHeader_To_route_RouteSetHTTPHeader is an autogenerated conversion function.
func Convert_v1_RouteSetHTTPHeader_To_route_RouteSetHTTPHeader(in *routev1.RouteSetHTTPHeader, out *route.RouteSetHTTPHeader, s conversion.Scope) error {
	return autoConvert_v1_RouteSetHTTPHeader_To_route_RouteSetHTTPHeader(in, out, s)
}

func autoConvert_route_RouteSetHTTPHeader_To_v1_RouteSetHTTPHeader(in *route.RouteSetHTTPHeader, out *routev1.RouteSetHTTPHeader, s conversion.Scope) error {
	out.Value = in.Value
	return nil
}

// Convert_route_RouteSetHTTPHeader_To_v1_RouteSetHTTPHeader is an autogenerated conversion function.
func Convert_route_RouteSetHTTPHeader_To_v1_RouteSetHTTPHeader(in *route.RouteSetHTTPHeader, out *routev1.RouteSetHTTPHeader, s conversion.Scope) error {
	return autoConvert_route_RouteSetHTTPHeader_To_v1_RouteSetHTTPHeader(in, out, s)
}

func autoConvert_v1_RouteSpec_To_route_RouteSpec(in *routev1.RouteSpec, out *route.RouteSpec, s conversion.Scope) error {
	out.Host = in.Host
	out.Subdomain = in.Subdomain
	out.Path = in.Path
	if err := Convert_v1_RouteTargetReference_To_route_RouteTargetReference(&in.To, &out.To, s); err != nil {
		return err
	}
	out.AlternateBackends = *(*[]route.RouteTargetReference)(unsafe.Pointer(&in.AlternateBackends))
	out.Port = (*route.RoutePort)(unsafe.Pointer(in.Port))
	out.TLS = (*route.TLSConfig)(unsafe.Pointer(in.TLS))
	out.WildcardPolicy = route.WildcardPolicyType(in.WildcardPolicy)
	out.HTTPHeaders = (*route.RouteHTTPHeaders)(unsafe.Pointer(in.HTTPHeaders))
	return nil
}

// Convert_v1_RouteSpec_To_route_RouteSpec is an autogenerated conversion function.
func Convert_v1_RouteSpec_To_route_RouteSpec(in *routev1.RouteSpec, out *route.RouteSpec, s conversion.Scope) error {
	return autoConvert_v1_RouteSpec_To_route_RouteSpec(in, out, s)
}

func autoConvert_route_RouteSpec_To_v1_RouteSpec(in *route.RouteSpec, out *routev1.RouteSpec, s conversion.Scope) error {
	out.Host = in.Host
	out.Subdomain = in.Subdomain
	out.Path = in.Path
	if err := Convert_route_RouteTargetReference_To_v1_RouteTargetReference(&in.To, &out.To, s); err != nil {
		return err
	}
	out.AlternateBackends = *(*[]routev1.RouteTargetReference)(unsafe.Pointer(&in.AlternateBackends))
	out.Port = (*routev1.RoutePort)(unsafe.Pointer(in.Port))
	out.TLS = (*routev1.TLSConfig)(unsafe.Pointer(in.TLS))
	out.WildcardPolicy = routev1.WildcardPolicyType(in.WildcardPolicy)
	out.HTTPHeaders = (*routev1.RouteHTTPHeaders)(unsafe.Pointer(in.HTTPHeaders))
	return nil
}

// Convert_route_RouteSpec_To_v1_RouteSpec is an autogenerated conversion function.
func Convert_route_RouteSpec_To_v1_RouteSpec(in *route.RouteSpec, out *routev1.RouteSpec, s conversion.Scope) error {
	return autoConvert_route_RouteSpec_To_v1_RouteSpec(in, out, s)
}

func autoConvert_v1_RouteStatus_To_route_RouteStatus(in *routev1.RouteStatus, out *route.RouteStatus, s conversion.Scope) error {
	out.Ingress = *(*[]route.RouteIngress)(unsafe.Pointer(&in.Ingress))
	return nil
}

// Convert_v1_RouteStatus_To_route_RouteStatus is an autogenerated conversion function.
func Convert_v1_RouteStatus_To_route_RouteStatus(in *routev1.RouteStatus, out *route.RouteStatus, s conversion.Scope) error {
	return autoConvert_v1_RouteStatus_To_route_RouteStatus(in, out, s)
}

func autoConvert_route_RouteStatus_To_v1_RouteStatus(in *route.RouteStatus, out *routev1.RouteStatus, s conversion.Scope) error {
	out.Ingress = *(*[]routev1.RouteIngress)(unsafe.Pointer(&in.Ingress))
	return nil
}

// Convert_route_RouteStatus_To_v1_RouteStatus is an autogenerated conversion function.
func Convert_route_RouteStatus_To_v1_RouteStatus(in *route.RouteStatus, out *routev1.RouteStatus, s conversion.Scope) error {
	return autoConvert_route_RouteStatus_To_v1_RouteStatus(in, out, s)
}

func autoConvert_v1_RouteTargetReference_To_route_RouteTargetReference(in *routev1.RouteTargetReference, out *route.RouteTargetReference, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	out.Weight = (*int32)(unsafe.Pointer(in.Weight))
	return nil
}

// Convert_v1_RouteTargetReference_To_route_RouteTargetReference is an autogenerated conversion function.
func Convert_v1_RouteTargetReference_To_route_RouteTargetReference(in *routev1.RouteTargetReference, out *route.RouteTargetReference, s conversion.Scope) error {
	return autoConvert_v1_RouteTargetReference_To_route_RouteTargetReference(in, out, s)
}

func autoConvert_route_RouteTargetReference_To_v1_RouteTargetReference(in *route.RouteTargetReference, out *routev1.RouteTargetReference, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	out.Weight = (*int32)(unsafe.Pointer(in.Weight))
	return nil
}

// Convert_route_RouteTargetReference_To_v1_RouteTargetReference is an autogenerated conversion function.
func Convert_route_RouteTargetReference_To_v1_RouteTargetReference(in *route.RouteTargetReference, out *routev1.RouteTargetReference, s conversion.Scope) error {
	return autoConvert_route_RouteTargetReference_To_v1_RouteTargetReference(in, out, s)
}

func autoConvert_v1_RouterShard_To_route_RouterShard(in *routev1.RouterShard, out *route.RouterShard, s conversion.Scope) error {
	out.ShardName = in.ShardName
	out.DNSSuffix = in.DNSSuffix
	return nil
}

// Convert_v1_RouterShard_To_route_RouterShard is an autogenerated conversion function.
func Convert_v1_RouterShard_To_route_RouterShard(in *routev1.RouterShard, out *route.RouterShard, s conversion.Scope) error {
	return autoConvert_v1_RouterShard_To_route_RouterShard(in, out, s)
}

func autoConvert_route_RouterShard_To_v1_RouterShard(in *route.RouterShard, out *routev1.RouterShard, s conversion.Scope) error {
	out.ShardName = in.ShardName
	out.DNSSuffix = in.DNSSuffix
	return nil
}

// Convert_route_RouterShard_To_v1_RouterShard is an autogenerated conversion function.
func Convert_route_RouterShard_To_v1_RouterShard(in *route.RouterShard, out *routev1.RouterShard, s conversion.Scope) error {
	return autoConvert_route_RouterShard_To_v1_RouterShard(in, out, s)
}

func autoConvert_v1_TLSConfig_To_route_TLSConfig(in *routev1.TLSConfig, out *route.TLSConfig, s conversion.Scope) error {
	out.Termination = route.TLSTerminationType(in.Termination)
	out.Certificate = in.Certificate
	out.Key = in.Key
	out.CACertificate = in.CACertificate
	out.DestinationCACertificate = in.DestinationCACertificate
	out.InsecureEdgeTerminationPolicy = route.InsecureEdgeTerminationPolicyType(in.InsecureEdgeTerminationPolicy)
	out.ExternalCertificate = (*route.LocalObjectReference)(unsafe.Pointer(in.ExternalCertificate))
	return nil
}

// Convert_v1_TLSConfig_To_route_TLSConfig is an autogenerated conversion function.
func Convert_v1_TLSConfig_To_route_TLSConfig(in *routev1.TLSConfig, out *route.TLSConfig, s conversion.Scope) error {
	return autoConvert_v1_TLSConfig_To_route_TLSConfig(in, out, s)
}

func autoConvert_route_TLSConfig_To_v1_TLSConfig(in *route.TLSConfig, out *routev1.TLSConfig, s conversion.Scope) error {
	out.Termination = routev1.TLSTerminationType(in.Termination)
	out.Certificate = in.Certificate
	out.Key = in.Key
	out.CACertificate = in.CACertificate
	out.DestinationCACertificate = in.DestinationCACertificate
	out.InsecureEdgeTerminationPolicy = routev1.InsecureEdgeTerminationPolicyType(in.InsecureEdgeTerminationPolicy)
	out.ExternalCertificate = (*routev1.LocalObjectReference)(unsafe.Pointer(in.ExternalCertificate))
	return nil
}

// Convert_route_TLSConfig_To_v1_TLSConfig is an autogenerated conversion function.
func Convert_route_TLSConfig_To_v1_TLSConfig(in *route.TLSConfig, out *routev1.TLSConfig, s conversion.Scope) error {
	return autoConvert_route_TLSConfig_To_v1_TLSConfig(in, out, s)
}
